package np.com.softwel.suswa_nwash.model

data class FieldData(
    val id: Int = 0,
    val lgName : String = "",
    val ward:Int = 0,
    val scheme : String = "",
    val surveyDate: String = "",
    val BenHH : Long = 0,
    val BenPop : Long = 0,
    val report : String = "",
    val structureName : String = "",
    val issues : String = "",
    val solution : String = "",
    val functionalStatus : String = "",
    val registrationRenewalWUSC : String = "",
    val completenessWUSC : String = "",
    val regularityMeetingWUSC :  String = "",
    val appointmentMobilization : String = "",
    val planPreparationImplementation : String = "",
    val OMprodureImplementation : String = "",
    val AGM : String = "",
    val sparePartManagement : String = "",
    val annualReview : String = "",
    val accountManagement : String = "",
    val affiliation : String = "",
    val OMfundTraffic : String = "",
    val OmfundStatus : String = "",
    val waterQuantity : String = "",
    val waterAccessibility : String = "",
    val waterAvailability : String = "",
    val waterQuality : String = "",
    val incomeExpenditureRatio : String = "",
    val SSCreporting : String = "",
)
